---
output:
  html_document: default
  pdf_document: default
---
```{r}
library(tidyverse)
library(Stat2Data)
data("Hawks")
```

# 1 Data Wrangling

## 1.1 Select and filter

### Q1
```{r}
hSF<-Hawks %>%
  filter(Species=='RT' & Weight >=1000) %>%
  select(Wing, Weight, Tail)
head(hSF)
```
### Q2
3 var
data can be used to classify Hawks?

## 1.2 The arrange function

### Q1
```{r}
sort_hSF<-hSF %>%
  arrange(Wing)
head(sort_hSF, 5)
```

## 1.3 Join and rename functions
```{r}
species_code <- c("CH", "RT", "SS")
species_name_full <- c("Cooper's", "Red-tailed", "Sharp-shinned")
hawkSpeciesNameCodes <- data.frame(species_code, species_name_full)
hawksFullName <- Hawks %>%
  select(Species, Wing, Weight, Tail,Culmen,Hallux,StandardTail, Tarsus, Crop) %>%
  rename(species_code = Species)

temp_hawksFullName<-left_join(hawksFullName, hawkSpeciesNameCodes)
final<-select(temp_hawksFullName, species_name_full, Wing, Weight,Tail,Culmen,Hallux,StandardTail, Tarsus, Crop, -species_code)
final<-final %>% rename(Species = species_name_full)
head(final, 7)
```

## 1.4 The mutate function

### Q1
```{r}
t<-Hawks %>% 
  select(Species, Wing, Weight) %>% 
  mutate(bird_BMI=1000*Weight/Wing^2) %>% 
  arrange(desc(bird_BMI))
head(t, 8)
```

## 1.5 Summarize and group-by functions

### Q1
```{r}
final %>%
  group_by(Species) %>%
  summarize(num_rows=n(), mn_wing=round(mean(Wing)), md_wing=median(Wing, na.rm=TRUE), t_mn_wing=round(mean(Wing, 0.1)), b_wt_ratio=round(max(Wing/Tail, na.rm=TRUE),2))
```

### Q2
```{r}
final %>%
  select(Species,Wing,Weight,Culmen,Hallux,Tail,StandardTail, Tarsus, Crop) %>%
  group_by(Species) %>%
  summarize(across(everything(), ~sum(is.na(.x))))
```

# 2.Tidy data and iteration
## 2.1.Missing data and iteration

### Q1
tidyverse

### Q2
```{r}
impute_by_median<-function(x) {
  me<-median(x,na.rm = 1)
  print(me)
  impute_f<-function(z){
    if(is.na(z)){ 
      return(me)
    }else{ 
      return(z)
    } 
  }
  return(map_dbl(x,impute_f))
}
v<-c(1,2,NA,4)
impute_by_median(v)
```

### Q3
```{r}
x<-c(seq(0,10,0.1))
linear_fo<-function(x) {
  5*x+1
}
y<-linear_fo(x)
df_xy<-data.frame(x,y)
df_xy%>%head(5)
```

### Q4
```{r}
# df_xy_new<-df_xy
# df_xy_new%>% mutate(z=map2_dbl(x,y,~.x+.y))%>% head(5)
sometimes_missing<-function(index, value) {
  if (index %% 5 == 0) {
    return (NA)
  } else {
    return (value)
  }
}
x<-data.frame(x)
df_xy_missing<-x %>%
  mutate(y=map2_dbl(x, row_number(), ~sometimes_missing(.y, 5*.x+1)))
head(df_xy_missing, 10)
```

### Q5
```{r}
df_xy_imputed<-df_xy_missing %>%
  mutate(y=impute_by_median(y))
head(df_xy_imputed)
```

## 2.2 Tidying data with pivot functions

```{r}
library(readxl)
folder_path<-"/Users/fanxinwei/R_learning_Bristol/Lab2/"
file_name<-"HockeyLeague.xlsx"
file_path<-paste(folder_path,file_name,sep="")
wins_data_frame<-read_excel(file_path,sheet="Wins")
losses_data_frame<-read_excel(file_path,sheet="Losses")
wins_data_frame%>% select(1:5)%>% head(3)
```

### Q1
```{r}
# 运行一次
wins_data_frame <- wins_data_frame %>%
 rename(Teams = ...1)

wins_tidy<-wins_data_frame %>%
  pivot_longer(as.character(seq(1990, 2020)), names_to=('Year'), values_to=('win_of_total')
  )

wins_tidy<-wins_tidy %>%
  separate(win_of_total, into=c("Win", "Total"), sep="of")
wins_tidy %>%dim()
wins_tidy%>%head(5)
```

### Q2
```{r}
# 运行一次
losses_data_frame <- losses_data_frame %>%
rename(Teams = ...1)

losses_tidy<-losses_data_frame %>%
  pivot_longer(as.character(seq(1990, 2020)), names_to=('Year'), values_to=('loss_of_total')
  )

losses_tidy<-losses_tidy %>%
  separate(loss_of_total, into=c("Losses", "Total"), sep="of")
losses_tidy%>%head(5)
```

### Q3
```{r}
hockey_df<-left_join(wins_tidy, losses_tidy)
hockey_df <- hockey_df %>%
  mutate(Draws=as.numeric(Total)-as.numeric(Win)-as.numeric(Losses)) %>%
  mutate(Wins_rt=as.numeric(Win)/as.numeric(Total)) %>%
  mutate(Losses_rt=as.numeric(Losses)/as.numeric(Total)) %>%
  mutate(Draws_rt=as.numeric(Draws)/as.numeric(Total)) 

hockey_df <- hockey_df %>%
  mutate(across(c(Win, Losses, Total), as.numeric),  
         Draws = Total - Win - Losses,
         across(c(Win, Losses, Draws), ~ . / Total, .names = "{.col}_rt"))
hockey_df%>%head(5)
```

### Q4
```{r}
tmp<-hockey_df %>%
  select(Teams, Win_rt, Losses_rt, Draws_rt) %>%
  group_by(Teams) %>%
  summarize(W_md=median(Win_rt), W_mn=mean(Win_rt),L_md=median(Losses_rt), L_mn=mean(Losses_rt),D_md=median(Draws_rt), D_mn=mean(Draws_rt)) %>%
  arrange(desc(W_md))
tmp
```

# 3.Visualisation
## Q1
```{r}
tmp_3_1<-wins_tidy %>%
  filter(Teams=="Ducks")

univar_plot <- ggplot(data=tmp_3_1, aes(as.numeric(Win))) + xlab("wins")
univar_plot+geom_histogram(binwidth = 3)+ylab("Count")
```

## Q2
```{r}
univar_plot+geom_density(adjust=0.5)+ylab('Density')
univar_plot+geom_density(adjust=2)+ylab('Density')
```

## Q3
```{r}
wins_team<-wins_tidy %>%
  pivot_wider(names_from = Teams, values_from = Win) %>%
  select(-Total)
mass_flipper_scatter <- ggplot(data=wins_team, aes(y=Eagles, x=Ducks))+
  xlab("Ducks") + ylab("Eagles")
mass_flipper_scatter+geom_point(size=1)
```
