---
title: "Assignment 3"
author: "Xinwei Fan"
date: "2023-10-11"
output: html_document # you can change to other output format if you want
---


```{r}
library(tidyverse)
library(Stat2Data)
data("Hawks")
```

# 1. Exploratory data analysis

```{r}
head(Hawks)
```
## 1.1 (Q1)   
<!-- Include your answers for each question under a second level heading eg ## 1.1 (Q1) -->
**** insert your solutions here *****
```{r}
HawksTail <- Hawks$Tail
HawksTail <- HawksTail[1:6]
HawksTail
tail_mean <- mean(HawksTail)
tail_mean
tail_med <- median(HawksTail)
tail_med
```
## 1.2 (Q1)
```{r}
Hawks %>%
  summarize(Wing_mean=mean(Wing, na.rm=TRUE), Wing_t_mean=mean(Wing, trim=0.50, na.rm=TRUE), Wind_med=median(Wing, na.rm=TRUE), Weight_mean=mean(Weight, na.rm=TRUE), Weight_t_mean=mean(Weight, trim=0.50, na.rm=TRUE), Weight_med=median(Weight, na.rm=TRUE))
```
## 1.2 (Q2)
```{r}
Hawks %>%
  group_by(Species) %>%
  summarize(Wing_mean=mean(Wing, na.rm=TRUE), Wing_t_mean=mean(Wing, trim=0.50, na.rm=TRUE), Wind_med=median(Wing, na.rm=TRUE), Weight_mean=mean(Weight, na.rm=TRUE), Weight_t_mean=mean(Weight, trim=0.50, na.rm=TRUE), Weight_med=median(Weight, na.rm=TRUE))
```
## 1.3 (Q1)
aA+b
```{r}
A <- mean(HawksTail)
result_1 <- A*2+3
result_1
HawksTail_y <- HawksTail*2+3
result_2 <- mean(HawksTail_y)
result_2
```
## 1.3 (Q2)
```{r}
tail_var<-var(HawksTail_y, na.rm=TRUE)
tail_var
tail_sd<-sd(HawksTail_y, na.rm=TRUE)
tail_sd
```
## 1.4
```{r}
hal<-Hawks$Hallux
hal<-hal[!is.na(hal)]
outlier_val<-100
num_outliers<-10
# 添加10个100的outlier
corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
mean(hal)
mean(corrupted_hal)
num_outliers_vect<-seq(0,1000) 
means_vect<-c() 
for(num_outliers in num_outliers_vect) { 
  corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
  means_vect<-c(means_vect,mean(corrupted_hal)) 
}
means_vect
```
## 1.4 (Q1)
```{r}
medians_vect<-c() 
for(num_outliers in num_outliers_vect) { 
  corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
  medians_vect<-c(medians_vect,median(corrupted_hal)) 
}
medians_vect
```
## 1.4 (Q2)
```{r}
t_means_vect<-c() 
for(num_outliers in num_outliers_vect) { 
  corrupted_hal<-c(hal,rep(outlier_val,times=num_outliers))
  t_means_vect<-c(t_means_vect,mean(corrupted_hal, trim=0.1)) 
}
t_means_vect
```
## 1.4 (Q2)
```{r}
df_means_medians<-data.frame(num_outliers=num_outliers_vect,mean=means_vect, t_mean=t_means_vect,median=medians_vect)
df_means_medians
df_means_medians%>% pivot_longer(!num_outliers,names_to="Estimator",values_to="Value")%>% ggplot(aes(x=num_outliers,color=Estimator,linetype=Estimator,y=Value))+ geom_line()+xlab("Numberofoutliers")
```
median? because it's very steady
## 1.5 (Q1)
```{r}
ggplot(data=Hawks, aes(x=Species, y=Weight))+geom_boxplot()+xlab('Species') + ylab("Weight")
```
## 1.5 (Q2)
```{r}
Hawks %>%
  group_by(Species) %>%
  summarize(quantile025=quantile(Weight, probs = 0.25, na.rm=TRUE),
            quantile050=quantile(Weight, probs = 0.5, na.rm=TRUE),
            quantile075=quantile(Weight, probs = 0.75, na.rm=TRUE))
  
```
## 1.5 (Q3)
```{r}
num_outliers <- function(vec) {
  q25 <- quantile(vec, probs = 0.25, na.rm=TRUE)
  q75 <- quantile(vec, probs = 0.75, na.rm=TRUE)
  IQR <- q75 - q25
  outliers <- sum(vec < (q25 - 1.5 * IQR) | vec > (q75 + 1.5 * IQR), na.rm = TRUE)
  return (outliers)
}
num_outliers(c(0,40,60,185))
```
## 1.5 (Q4)
```{r}
Hawks %>%
  group_by(Species) %>%
  summarise(num_outliers_weight=num_outliers(Weight))
```
## 1.6 (Q1)
```{r}
S <- cov(Hawks$Weight, Hawks$Wing, use='complete.obs')
R <- cor(Hawks$Weight, Hawks$Wing, use='complete.obs')
S
R
```
## 1.6 (Q2)
acS
acR/|a||c|
```{r}
S_ <- cov(Hawks$Weight * 2.4 + 7.1, Hawks$Wing * -1 + 3, use='complete.obs')
R_ <- cor(Hawks$Weight * 2.4 + 7.1, Hawks$Wing * -1 + 3, use='complete.obs')
S_
R_
S_manual <- 2.4 * -1 * S
R_manual <- 2.4 * -1 * R / abs(2.4) * abs(-1)
S_manual
R_manual
```

# 2. Random experiments, events and sample spaces, and the set theory

....

# 3. Visualisation

## 3 (Q1)

## 3 (Q2)

.....



